version: "3"
services:
  app:
    container_name: koa-mongo
    restart: always
    build: .
    ports:
      - "5001:5000"
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db/mongo:/data/db
    ports:
      - "27018:27017"
  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
